### PR TITLE
Add several modifications

### PR DESCRIPTION
**Pull request by jordi-pages**
- Add param to select corner refinement algorithm
- Add rviz marker representing the AruCo patch detected
- Use double rather than float in aruco_ros_utils

### CODE REVIEW

**Comment by bmagyar** [comment]
:+1: 
Some hidden gems! I wasn't aware of the corner refinement methods! 
Do you think it'd make sense to add these to the dynamic reconfigure too?

**Comment by jordi-pages** [comment]
Be my guest! For the moment I prefer merging and afterwards we can add it to the dynamic reconfigure.

**Comment by bmagyar** [comment]
:+1: for merge

**Comment by jordi-pages** [comment]
By the way, I've seen that the dynamic_reconfigure server is only implemented in simple_double.cpp... Just for the record.

**Pull request merged**
